---
- hosts: masternode
  gather_facts: false
  tasks:
    - name: get join command
      become: no
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"


    - name: print join_command
      debug:
        var: join_command

- hosts: workernode
  gather_facts: false
  tasks:
    - name: joing the worker nodes
      shell: join_command  
