version: '3.0'

services:

  registry:
    container_name: docker-registry
    restart: always
    image: registry:latest
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/registry.crt
      REGISTRY_HTTP_TLS_KEY: /certs/registry.key
    ports:
      - 5000:5000
    volumes:
      - registry-data:/var/lib/registry
      - ./certs:/certs

volumes:
  registry-data: {}
